# File: checkout.py
# Author: Braden Morrison
# Date: 06/20/2023
# Section: 700
# E-mail: bradenmorrison@tamu.edu 
# Description: 

import time

num_titles = int(input("Enter the number of unique book titles: "))
x = 0
subtotal = 0.00
p1 = 0
p2 = 0
p3 = 0

while x < num_titles:
    print()
    x += 1
    if x == 1:
        print("Book title #", x, ":", sep='', end= ' ')
        title = str(input())
        print('Book (', title, ') sticker price:', sep='', end= ' ')
        price = float(input())
        print('Book (', title, ') quantity:', sep='', end= ' ')
        quantity = int(input())
        print('Book (', title, ') publication year:', sep='', end= ' ')
        year = int(input())
        print('Book (', title, ') ISBN:', sep='', end= ' ')
        isbn = int(input())
        '''
        i1 = isbn
        temp=i1
        rev=0
        while(i1>0):
            dig=isbn%10
            rev=rev*10+dig
            i1=i1//10
        if(temp==rev):
            price -= 10
        '''
        if isbn == 678876:
            price = 0
        elif isbn == 12322321:
            price -= 50
            
        price = price * quantity
        if year <= 1986:
            price = 0.00
        if year >= 1990 and year <= 2000:
            price = price * 0.75
        if year == 2021:
            price = price * 1.05
        p1 = price
        subtotal += price

    if x == 2:
        print("Book title #", x, ":", sep='', end= ' ')
        title2 = str(input())
        print('Book (', title2, ') sticker price:', sep='', end= ' ')
        price2 = float(input())
        print('Book (', title2, ') quantity:', sep='', end= ' ')
        quantity2 = int(input())
        print('Book (', title2, ') publication year:', sep='', end= ' ')
        year2 = int(input())
        print('Book (', title2, ') ISBN:', sep='', end= ' ')
        isbn2 = int(input())
        '''
        i2 = isbn2
        while(i2>0):
            dig=i2%10
            rev=rev*10+dig
            i2=i2//10
        if(temp==rev):
            price2 -= 10
        '''
        if isbn2 == 678876:
            price2 = 0
        elif isbn2 == 12322321:
            price2 -= 50
            
        price2 = price2 * quantity2
        if year2 <= 1986:
            price2 = 0.00
        if year2 >= 1990 and year2 <= 2000:
            price2 = price2 * 0.75
        if year2 == 2021:
            price2 = price2 * 1.05
        p2 = price2
        subtotal += price2

    if x == 3:
        print("Book title #", x, ":", sep='', end= ' ')
        title3 = str(input())
        print('Book (', title3, ') sticker price:', sep='', end= ' ')
        price3 = float(input())
        print('Book (', title3, ') quantity:', sep='', end= ' ')
        quantity3 = int(input())
        print('Book (', title3, ') publication year:', sep='', end= ' ')
        year3 = int(input())
        print('Book (', title3, ') ISBN:', sep='', end= ' ')
        isbn3 = int(input())
        '''
        i3 = isbn3
        while(i3>0):
            dig=i3%10
            rev=rev*10+dig
            i3=i3//10
        if(temp==rev):
            price3 -= 10
        '''
        if isbn3 == 678876:
            price3 = 0
        elif isbn3 == 12322321:
            price3 -= 50.00
            
        price3 = price3 * quantity3
        if year3 <= 1986:
            price3 = 0.00
        if year3 >= 1990 and year3 <= 2000:
            price3 = price3 * 0.75
        if year3 == 2021:
            price3 = price3 * 1.05
        p3 = price3
        subtotal += price3
   
  
tax = subtotal * 0.0825
tax = round(tax,2)
total = subtotal + tax
total = round(total,2)
subtotal = round(subtotal,2)
if p1 == 0.0:
    p1 = 0
p1 = round(p1, 2)
p2 = round(p2, 2)
p3 = round(p3, 2)
print()



print('110 Library Receipt')
print('Date: June 21, 2023')
current_time = time.strftime("%H:%M")
print('Time:', current_time)
print('Number of unique book titles:', num_titles)
print()

print(f'{"Quantity":10}{"Title":30}{"ISBN":20}{"Price":10}')
print(f'{quantity:<10}{title:<30}{isbn:<20}{"$"}{p1:<9}')
if x == 2:
    print(f'{quantity2:<10}{title2:<30}{isbn2:<20}{"$"}{p2:<9}')
if x == 3:
    print(f'{quantity3:<10}{title3:<30}{isbn3:<20}{"$"}{p3:<9}')
print()
if subtotal == 0:
    z = int(0)
    print(f'{"Subtotal":<10}{"$":>51}{z:<9}')
else:
    print(f'{"Subtotal":<10}{"$":>51}{subtotal:<9}')
print(f'{"Tax":<10}{"$":>51}{tax:<9}')
print(f'{"Total":<10}{"$":>51}{total:<9}')
print('Generated by Library Management App')


